# Makefile for linear multistep examples
#
# Daniel R. Reynolds
# Math 6321 @ SMU
# Fall 2020

# compiler & flags
CXX = g++
#CXXFLAGS = -O -std=c++11
CXXFLAGS = -O0 -g -std=c++11
INCS = -I ../shared
LIBS = -larmadillo

# executable targets
all : driver.exe

driver.exe : driver.cpp lmm.cpp
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LIBS) $(INCS)


# utilities
clean :
	\rm -rf *.txt *.exe *~ *.dSYM
